name: ludvig
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.4.0
  - pytorch-cuda=11.8
  - torchvision
  - open-clip-torch
  - jaxtyping
  - matplotlib
  - omegaconf
  - opencv
  - Pillow
  - plyfile
  - PyYAML
  - scikit-learn
  - scikit-image
  - scipy
  - tqdm
  - setuptools
  - pip
  - pip:
    - gaussiansplatting/submodules/diff-gaussian-rasterization
    - gaussiansplatting/submodules/simple-knn
    - git+https://github.com/facebookresearch/segment-anything.git
    - git+https://github.com/facebookresearch/sam2.git
    - xformers
    - --extra-index-url https://download.pytorch.org/whl/cu118
