tag: "singleview_sam"
dst_dir: logs/SPIn
evaluation:
  name: evaluation.spin_nvos.segmentation.SegmentationSPInSAM
  segmentation_3d: False
  single_view: True
  scribbles_are_masks: True
  maskdir: dataset/SPIn-NeRF_masks/{}
  model: 
    name: utils.sam.load_sam
    ckpt_path: ./checkpoints/sam2_hiera_large.pt #sam_vit_h_4b8939.pth #
