tag: "xdif"
dst_dir: logs/SPIn
prune_gaussians: 600000
feature:
  name: predictors.dino.DINOv2Dataset
  dino_ckpt: ./checkpoints/dinov2_vitg14_reg4_pretrain.pth
  dino_cfg: ./dinov2/configs/vitg14_pretrain.yaml
  n_components: 40
  eigval_weighting: True
  sliding_window:
    name: utils.sliding_windows.SlidingWindow
    crop_size: 840
    stride: 200
evaluation:
  name: evaluation.spin_nvos.segmentation.SegmentationSPInDINOv2
  segmentation_3d: False
  logreg: .1
  maskdir: dataset/SPIn-NeRF_masks/{}
